apiVersion: v1
kind: Service
metadata:
  name: twittertrend-service
  namespace: imran
spec:
  type: NodePort
  selector:
    app: twittertrend
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
